services:
  mongodb:
    image: mongo:latest
    container_name: mongodbtest1
    networks:
      - mern-network
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server1
    ports:
      - "9000:9000"
    environment:
      - MONGO_URI=mongodb://root:example@mongodb:27017/?authSource=admin
    depends_on:
      - mongodb
    networks:
      - mern-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client1
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge
